import { ChunkExtractor } from '@loadable/server';
import Koa from 'koa';
import _ from 'lodash';
import path from 'path';
import React from 'react';
import { renderToNodeStream } from 'react-dom/server';
import { Provider } from 'react-redux';
import { StaticRouter } from 'react-router-dom';

import { AppShell } from '~app/containers';
import styles from '~app/css/styles.css';

import { initStoreForSSR } from './initStore';

// this is the stats file generated by webpack loadable plugin
const statsFile = path.resolve('./dist/loadable-stats.json');

export const SSR = async (app: Koa, ctx: Koa.ParameterizedContext) => {
  const nonce = _.get(app, 'context.state.nonce', '');
  // need to be set for server streaming, if not set, then koa will crap out
  ctx.respond = false;
  ctx.type = 'text/html';

  // set stricter whitelist for prod
  const local = __DEV__ ? "'self' 127.0.0.1:* 0.0.0.0:*" : "'self'";
  // webpack debug mode seems to use eval(?) so disable the CSP in debug mode
  // i think this is mostly fine, considering the CSP runs for every other case
  const CSP = !__DEBUG__ ? `<meta charset="UTF-8" /><meta http-equiv="Content-Security-Policy" content="base-uri 'none'; connect-src ${local}; default-src 'none'; block-all-mixed-content; font-src ${local}; form-action ${local}; img-src ${local} https://*.libravatar.org https://s3.amazonaws.com https://i.picsum.photos https://picsum.photos; manifest-src ${local}; object-src 'none'; script-src ${local} ajax.googleapis.com 'nonce-${nonce}'; style-src ${local} 'nonce-${nonce}'">` : '';

  ctx.res.write(`<!DOCTYPE html><html lang="en"><head>${CSP}<title>Consensus - when you need to get organized.</title><style type="text/css" nonce="${nonce}">${styles}</style></head><body><div id="appRoot">`);

  const initRouterContext = {};
  const store = await initStoreForSSR(ctx);

  const extractor = new ChunkExtractor({ statsFile });
  const jsx = extractor.collectChunks(
    <Provider store={store as any}>
      <StaticRouter context={initRouterContext} location={ctx.request.url}>
        <AppShell />
      </StaticRouter>
    </Provider>,
  );

  const htmlStream = renderToNodeStream(jsx);
  htmlStream.pipe(ctx.res, {end: false});
  htmlStream.on('end', () => {
    // eslint-disable-next-line
    const fontConfig = `WebFontConfig={custom:{families:["Lab"],urls:["/static/fonts.css"]}};window.__PRELOADED_STATE__ = ${JSON.stringify(store.getState())}`;

    ctx.res.write(`</div><div id="portalRoot"></div>
      <script type="text/javascript" nonce="${nonce}">${fontConfig}</script>
      <script defer src="/vendor.bundle.js"></script>
      <script defer src="/main.js"></script>
      <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js" integrity="sha384-pvXSwSU09c+q9mPyY++ygUHWIYRoaxgnJ/JC5wcOzMb/NVVu+IDniiB9qWp3ZNWM" crossorigin="anonymous"></script>
      </body></html>`);
    ctx.res.end();
  });
};
