import { ChunkExtractor } from '@loadable/server';
import Koa from 'koa';
import path from 'path';
import React from 'react';
import { renderToNodeStream } from 'react-dom/server';
import { Provider } from 'react-redux';
import { StaticRouter } from 'react-router-dom';
import serialize from 'serialize-javascript';

import { AppShell } from '../containers';
import styles from '../css/styles.styl';
import { initStoreForSSR } from './initStore';

// this is the stats file generated by webpack loadable plugin
const statsFile = path.resolve('./dist/loadable-stats.json');

export const SSR = async (ctx: Koa.ParameterizedContext) => {
  // need to be set for server streaming, if not set, then koa will crap out
  ctx.respond = false;
  ctx.type = 'text/html';
  ctx.res.write(`<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8" /><title>Consensus - when you need to get organized.</title><style>${styles}</style></head><body><div id="appRoot">`);

  const initRouterContext = {};
  const store = await initStoreForSSR(ctx);

  ctx.status = 200;
  const extractor = new ChunkExtractor({ statsFile });
  const jsx = extractor.collectChunks(
    <Provider store={store as any}>
      <StaticRouter context={initRouterContext} location={ctx.request.url}>
        <AppShell />
      </StaticRouter>
    </Provider>
  );
  const htmlStream = renderToNodeStream(jsx);

  htmlStream.pipe(ctx.res, {end: false});
  htmlStream.on('end', () => {
    // eslint-disable-next-line
    const fontConfig = `WebFontConfig={custom:{families:["Ivar","Lab","LabBlack","Eksell"],urls:["/static/fonts.css"]}};window.__PRELOADED_STATE__ = ${serialize(store.getState())}`;

    ctx.res.write(`</div><div id="portalRoot"></div>
      <script nonce="${ctx.state.locals.nonce}">${fontConfig}</script>
      <script defer src="/vendor.main.js"></script>
      <script defer src="/main.js"></script>
      <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js"></script>
      </body></html>`);
    ctx.res.end();
  });
};
