version: '3'
services:
  db:
    container_name: db
    image: postgres:11.2-alpine
    # networks:
    #   - backend
    ports:
      - "54320:5432"
    volumes:
      - "db_data:/var/lib/postgresql/data"

  redis:
    container_name: redis
    # command: ["redis-server", "--bind", "redis", "--port", "6379"]
    image: redis:alpine
    # networks:
    #   - backend
    sysctls:
      # fixes warning when using redis with the barebones alpine image
      net.core.somaxconn: '511'
