# for running the site in production mode locally as close to real prod as possible
version: '3'
services:
  prod:
    image: consensusdocker/test
    container_name: prod_local
    working_dir: /app
    # command here overrides CMD in Dockerfile. but Dockerfile requires CMD to be valid
    command: 'npm run prod'
    depends_on:
      - db
      - redis
    environment:
      - DB=development #eventually change to production
      - DEBUG=false
      - ENABLE_IPV6=true
      - NETWORK_ACCESS=internal
      - NODE_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_DEV_PW=${DB_DEV_PW}
      - DB_PROD_PW=${DB_PROD_PW}
      - DB_TEST_PW=${DB_TEST_PW}
      - MAXMIND_LICENSE_KEY=${MAXMIND_LICENSE_KEY}
      - LOG_LEVEL=${LOG_LEVEL}
      - PEPPER=${PEPPER}
      - VIRTUAL_HOST=consensus.local
      - VIRTUAL_PORT=3001
      - VIRTUAL_PROTO=https
    expose:
      - 3001
    volumes:
      - .:/app
      - node_modules:/app/node_modules

networks:
  default:
    external:
      name: nginx-proxy

volumes:
  db_data:
    external: true
  node_modules:
    external: true
