# local development w/ nodejs, koa and webpack debug mode activated
version: '3'
services:
  dev:
    container_name: dev
    command: "npx concurrently \"webpack -d --watch --config webpack/\" \"DEBUG=koa* nodemon --inspect ./dist/server.js\""
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB=development
      - DEBUG=false
      - NODE_ENV=development
      - VIRTUAL_HOST=consensus.local
      - VIRTUAL_PORT=3001
    image: node:12.3.0-alpine
    working_dir: /app
    volumes:
      - node_modules:/app/node_modules
      - .:/app

  db:
    container_name: db
    image: postgres:11.2-alpine
    ports:
      - "54320:5432"
    volumes:
      - "db_data:/var/lib/postgresql/data"

  redis:
    container_name: redis
    image: redis:alpine
    sysctls:
      # fixes warning when using the barebones alpine image
      net.core.somaxconn: '511'

volumes:
  db_data:
    external: true
  node_modules:
    external: true
