# for running the site in production mode locally as close to real prod as possible
version: '3'
services:
  prod:
    image: consensusdocker/qa
    container_name: prod_local
    working_dir: /app
    # command here overrides CMD in Dockerfile. but Dockerfile requires CMD to be valid
    command: 'npm run prod'
    depends_on:
      - redis
    environment:
      - DEBUG=false
      - NODE_ENV=production
      - DB=${DB_PROD}
      - DB_HOST=${DB_POOL_PUBLIC_HOST}
      - DB_USER=${DB_PROD_USER}
      - DB_PORT=${DB_POOL_PORT}
      - DB_PW=${DB_PROD_PW}
      - LOG_LEVEL=${LOG_LEVEL}
      - ENABLE_IPV6=true
      - NETWORK_ACCESS=internal
      - NO_INDEX=true
      - PEPPER=${PEPPER}
      - VIRTUAL_HOST=consensus.local
      - VIRTUAL_PORT=3001
      - VIRTUAL_PROTO=https
    expose:
      - 3001
    volumes:
      - .:/app
      - node_modules:/app/node_modules

  redis:
    container_name: redis
    image: redis:alpine
    restart: "always"
    sysctls:
      # fixes warning when using redis with the barebones alpine image
      net.core.somaxconn: '511'

networks:
  default:
    external:
      name: nginx-proxy

volumes:
  node_modules:
    external: true
