version: '3'
services:
  redis-server:
    image: 'redis'
  node-app:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "3001:3001"
  postgres:
    image: postgres:11.2-alpine
    ports:
      - "54320:5432"
    restart: always
    #   Set a volume some that database is not lost after shutting down the container.
    #   I used the name postgres-data but you can changed it to something else.
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
