# for running dev mode locally
version: '3'
services:
  dev:
    image: consensusdocker/test
    container_name: dev
    working_dir: /app
    command: "npx concurrently \"webpack --watch --config webpack/\" \"npx pm2-dev pm2.config.js --no-daemon\""
    depends_on:
      - redis
    environment:
      - DB=development
      - DEBUG=false
      - ENABLE_IPV6=true
      - NETWORK_ACCESS=internal
      - NODE_ENV=development
      - DB=${DB}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PORT=${DB_PORT}
      - DB_DEV_PW=${DB_DEV_PW}
      - MAXMIND_LICENSE_KEY=${MAXMIND_LICENSE_KEY}
      - LOG_LEVEL=${LOG_LEVEL}
      - PEPPER=${PEPPER}
      - VIRTUAL_HOST=consensus.local
      - VIRTUAL_PORT=3001
      - VIRTUAL_PROTO=https
    expose:
      - 3001
    volumes:
      - .:/app
      - node_modules:/app/node_modules

# connect our localhost to the nginx reverse proxy
networks:
  default:
    external:
      name: nginx-proxy

volumes:
  node_modules:
    external: true
