version: '3'
services:
  prod:
    # comment out when running an image on the host
    build: .
    image: consensusdocker/test
    container_name: prod
    working_dir: /app
    # command here overrides CMD in Dockerfile. but Dockerfile requires CMD to be valid
    command: "npm run prod"
    depends_on:
      - db
      - redis
    ports:
      - "3001:3001"
    environment:
      - DB=development #eventually change to production
      - DEBUG=false
      - ENABLE_IPV6=true
      - NODE_ENV=development
      - DB_HOST=db
      - DB_DEV_PW=${DB_DEV_PW}
      - DB_PROD_PW=${DB_PROD_PW}
      - DB_TEST_PW=${DB_TEST_PW}
      - MAXMIND_LICENSE_KEY=${MAXMIND_LICENSE_KEY}
      - LOG_LEVEL=${LOG_LEVEL}
      - PEPPER=${PEPPER}
    restart: "always"

  db:
    container_name: db
    image: postgres:11.2-alpine
    ports:
      - "54320:5432"
    volumes:
      - "db_data:/var/lib/postgresql/data:z"
    restart: "always"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=consensus_dev
      - POSTGRES_PASSWORD=${DB_DEV_PW}

  redis:
    container_name: redis
    image: redis:alpine
    restart: "always"
    sysctls:
      # fixes warning when using redis with the barebones alpine image
      net.core.somaxconn: '511'

volumes:
  db_data:
    driver: local
