# for running production locally
version: '3'
services:
  prod:
    build: .
    image: consensusdocker:test
    container_name: prod
    working_dir: /app
    command: "webpack --config webpack && npx pm2-dev pm2.config.js --no-daemon"
    depends_on:
      - db
      - redis
    environment:
      - DB=development
      - DEBUG=false
      - ENABLE_IPV6=true
      - NETWORK_ACCESS=internal
      - NODE_ENV=production
      - VIRTUAL_HOST=consensus.local
      - VIRTUAL_PORT=3001
      - VIRTUAL_PROTO=https
    expose:
      - 3001
      - 9229
    restart: "always"
    # uncomment if running locally
    # volumes:
    #   - .:/app
    #   - node_modules:/app/node_modules

  db:
    restart: "always"

  redis:
    restart: "always"

# uncomment if running locally
# volumes:
#   db_data:
#     external: true
#   node_modules:
#     external: true
