# for running dev mode locally
version: '3'
services:
  dev:
    # uncomment to build a deployable image of the site in dev mode
    # build: .
    image: consensusdocker/test
    container_name: dev
    working_dir: /app
    command: "npx concurrently \"webpack --watch --config webpack/\" \"npx pm2-dev pm2.config.js --no-daemon\""
    depends_on:
      - db
      - redis
    environment:
      - DB=development
      - DEBUG=false
      - ENABLE_IPV6=true
      - NETWORK_ACCESS=internal
      - NODE_ENV=development
      - DB_HOST=${DB_HOST}
      - DB_DEV_PW=${DB_DEV_PW}
      - DB_PROD_PW=${DB_PROD_PW}
      - DB_TEST_PW=${DB_TEST_PW}
      - MAXMIND_LICENSE_KEY=${MAXMIND_LICENSE_KEY}
      - LOG_LEVEL=${LOG_LEVEL}
      - PEPPER=${PEPPER}
      - VIRTUAL_HOST=consensus.local
      - VIRTUAL_PORT=3001
      - VIRTUAL_PROTO=https
    expose:
      - 3001
      - 3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules

# connect our localhost to the nginx reverse proxy
networks:
  # backend:
  default:
    external:
      name: nginx-proxy

volumes:
  db_data:
    external: true
  node_modules:
    external: true
