version: '3'
services:
  debug:
    container_name: debug
    working_dir: /app
    command: "npx concurrently \"webpack --watch --config webpack/\" \"npx pm2-dev pm2.config.js --no-daemon\""
    depends_on:
      - db
      - redis
    environment:
      - DB=development
      - DEBUG=true
      - ENABLE_IPV6=true
      - NETWORK_ACCESS=internal
      - NODE_ENV=development
      - VIRTUAL_HOST=consensus.local
      - VIRTUAL_PORT=3001
      - VIRTUAL_PROTO=https
    expose:
      - 3001
      - 9229
    volumes:
      - .:/app
      - node_modules:/app/node_modules
