# just installs node_modules in the node_modules volume for development
# we separate this out from docker-compose cause it's pretty annoying to do
version: '3'
services:
  install:
    command: npm i --arch=x64 --platform=linux --no-progress
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    # change these to production when doing a prod build
    environment:
      - NODE_ENV=development
      - MAXMIND_LICENSE_KEY=${MAXMIND_LICENSE_KEY}

volumes:
  node_modules:
    external: true
