version: '3'
services:
  prod:
    # comment out when running an image on the host
    build: .
    image: consensusdocker/test
    container_name: prod
    working_dir: /app
    # command here overrides CMD in Dockerfile. but Dockerfile requires CMD to be valid
    command: "npm run prod"
    depends_on:
      - db
      - redis
    ports:
      - "3001:3001"
    environment:
      - DB=development #eventually change to production
      - DEBUG=false
      - ENABLE_IPV6=true
      - NODE_ENV=development
      - DB_HOST=${DB_HOST}
      - DB_DEV_PW=${DB_DEV_PW}
      - DB_PROD_PW=${DB_PROD_PW}
      - DB_TEST_PW=${DB_TEST_PW}
      - MAXMIND_LICENSE_KEY=${MAXMIND_LICENSE_KEY}
      - LOG_LEVEL=${LOG_LEVEL}
      - PEPPER=${PEPPER}
    # honestly, not sure if this is still needed because of port, but leaving since this was the state of the config when the site was finally reachable
    expose:
      - 3001
    restart: "always"

  db:
    restart: "always"

  redis:
    restart: "always"
