version: '3'
services:
  app:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "3001:3001"
      - "9229:9229"
    volumes:
      - ./volumes:/consensus
  postgres:
    image: postgres:11.2-alpine
    ports:
      - "54320:5432"
    restart: always
    volumes:
      - ./volumes:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    sysctls:
      net.core.somaxconn: '511'
