# for running dev mode locally
version: '3'
services:
  dev:
    image: consensusdocker/qa
    container_name: dev
    working_dir: /app
    command: "npx concurrently \"webpack --watch --config webpack/\" \"npx pm2-dev pm2.config.js --no-daemon\""
    depends_on:
      - redis
    environment:
      - DEBUG=false
      - NODE_ENV=development
      - DB=${DB_LOCAL}
      - DB_HOST=${DB_LOCAL_HOST}
      - DB_USER=${DB_LOCAL_USER}
      - DB_PORT=${DB_LOCAL_PORT}
      - DB_PW=${DB_LOCAL_PW}
      - LOG_LEVEL=${LOG_LEVEL}
      - ENABLE_IPV6=true
      - NETWORK_ACCESS=internal
      - NO_INDEX=true
      - PEPPER=${PEPPER}
      - VIRTUAL_HOST=consensus.local
      - VIRTUAL_PORT=3001
      - VIRTUAL_PROTO=https
    expose:
      - 3001
    volumes:
      - .:/app
      - node_modules:/app/node_modules

  redis:
    container_name: redis
    image: redis:alpine
    sysctls:
      # fixes warning when using redis with the barebones alpine image
      net.core.somaxconn: '511'

# connect our localhost to the nginx reverse proxy
networks:
  default:
    external:
      name: nginx-proxy

volumes:
  node_modules:
    external: true
