# production build only
version: '3'
services:
  app:
    build: .
    image: consensusdocker/test
    container_name: app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "3001:3001"
      - "9229:9229"
    restart: "on-failure"
    volumes:
      - nodemodules:/app/node_modules
      - .:/app

  db:
    image: postgres:11.2-alpine
    container_name: db
    ports:
      - "54320:5432"
    restart: "on-failure"
    volumes:
      - "db_data:/var/lib/postgresql/data"

  redis:
    image: redis:alpine
    container_name: redis
    sysctls:
      # fixes warning when using the barebones alpine image
      net.core.somaxconn: '511'

volumes:
  db_data:
    external: true
  nodemodules:
    external: true
