version: '3'
services:
  prod:
    build: .
    image: consensusdocker/test
    container_name: prod
    working_dir: /app
    networks:
      - web
    # links:
    #   - redis:redis
    # command here overrides CMD in Dockerfile. but Dockerfile requires CMD to be valid
    command: "npm run prod"
    depends_on:
      - db
      - redis
    environment:
      - DB=development #eventually change to production
      - DEBUG=false
      - ENABLE_IPV6=true
      - NODE_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_DEV_PW=${DB_DEV_PW}
      - DB_PROD_PW=${DB_PROD_PW}
      - DB_TEST_PW=${DB_TEST_PW}
      - MAXMIND_LICENSE_KEY=${MAXMIND_LICENSE_KEY}
      - LOG_LEVEL=${LOG_LEVEL}
      - PEPPER=${PEPPER}
      # - NETWORK_ACCESS=internal
      # - VIRTUAL_HOST=consensus.local
      # - VIRTUAL_PORT=3001
      # - VIRTUAL_PROTO=https
    expose:
      - 3001
    # uncomment if running locally
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    restart: "always"

  db:
    networks:
      - web
    restart: "always"

  redis:
    networks:
      - web
    restart: "always"

networks:
  web:

volumes:
  db_data:
  node_modules:
