version: '3'
services:
  prod:
    build: .
    image: consensusdocker/test
    container_name: prod_local
    working_dir: /app
    # command here overrides CMD in Dockerfile. but Dockerfile requires CMD to be valid
    command: "npm run prod"
    depends_on:
      - db
      - redis
    environment:
      - DB=development #eventually change to production
      - DEBUG=false
      - ENABLE_IPV6=true
      - NETWORK_ACCESS=internal
      - NODE_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_DEV_PW=${DB_DEV_PW}
      - DB_PROD_PW=${DB_PROD_PW}
      - DB_TEST_PW=${DB_TEST_PW}
      - MAXMIND_LICENSE_KEY=${MAXMIND_LICENSE_KEY}
      - LOG_LEVEL=${LOG_LEVEL}
      - PEPPER=${PEPPER}
      - VIRTUAL_HOST=consensus.local
      - VIRTUAL_PORT=3001
      - VIRTUAL_PROTO=https
    expose:
      - 3001
      - 3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    restart: "always"

  db:
    restart: "always"

  redis:
    restart: "always"

# connect our localhost to the nginx reverse proxy
networks:
  # backend:
  default:
    external:
      name: nginx-proxy

volumes:
  db_data:
    external: true
  node_modules:
    external: true
