export const initialState = {
  avatar: '',
  bio: '',
  city: '',
  cityId: 0,
  email: '',
  error: '',
  name: '',
  password: '',
  privateMemberships: false,
  privateRSVP: false,
  region: '',
  regionId: 0,
  sessionType: 'user' as ts.sessionType,
  username: '',
};
