export const initialState = {
  avatarEmail: '',
  bio: '',
  city: '',
  cityId: 0,
  email: '',
  name: '',
  password: '',
  privateMemberships: false,
  privateRSVP: false,
  region: '',
  regionId: 0,
  userAvatar: null as string | null,
  username: '',
};
