export const testGroup1 = {
  avatar: '',
  category: 'Union' as ts.category,
  city: 'New York',
  cityId: 1,
  country: 'United States',
  countryId: 1,
  description: '',
  deletionDeadline: '',
  email: 'testgroup1@test.com',
  id: 1,
  memberName: 'member',
  modName: 'facilitator',
  name: 'Tech Workers Coalition Chapter',
  region: 'New York',
  regionId: 1,
  handle: 'tech-workers-coalition-chapter',
  sessionType: 'group' as ts.sessionType,
  type: 'private' as ts.privacyEnum,
};
