export type tProps = {
  asList?: boolean,
  count?: number,
  groupType?: tRole,
  hoverIndex?: number,
  index?: number,
  isEditable?: boolean,
  leaveOrg: (ev: React.MouseEvent<HTMLButtonElement>, groupId: number) => void,
  group: tGroup,
  groups: tGroup[],
  pendingOrgs: tGroup[],
  roles: tRoleMap[],
  setHover: (hoverIndex: number | null, groupType?: tRole) => void,
  showCategory?: boolean,
  showLocation?: boolean,
  showType?: boolean,
  showPending?: boolean,
};
