version: "3.1"

services:
  nginx-proxy:
    network_mode: 'host'
    image: jwilder/nginx-proxy:alpine
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - ./certs:/etc/nginx/certs
      - ./consensus.conf:/etc/nginx/conf.d/consensus.conf:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

networks:
  default:
    external:
      name: nginx-proxy
